# Generated by Django 3.2.6 on 2021-08-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barter_name', models.CharField(max_length=20)),
                ('barter_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=20)),
                ('recipe_description', models.CharField(max_length=20)),
            ],
        ),
    ]
