# Generated by Django 3.2.5 on 2021-08-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_barter_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='barter_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.TextField(),
        ),
    ]
