# Generated by Django 3.2.3 on 2021-08-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210811_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='media/thumnail.png', upload_to=''),
        ),
    ]
