# Generated by Django 3.2.5 on 2021-08-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
