# Generated by Django 3.2.5 on 2021-08-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210811_1659'),
        ('users', '0008_remove_recipe_image'),
    ]

    operations = [
    ]
