# Generated by Django 3.2.3 on 2021-08-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='media/dafault_image.jpeg', upload_to=''),
        ),
    ]
