# Generated by Django 3.2.3 on 2021-08-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='media/thumnail.png', upload_to=''),
        ),
    ]
