# Generated by Django 3.2.5 on 2021-08-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
